### ISSUE TITLE
Library load error: {:error, {:bad_lib, 'Function not found \'ParentModule.SubModule\':get_unix_timestamp/0'}}

### ISSUE THREAD

**Issue by developerworks** [goertzenator/ruster_unsafe_demo#1]
I write a `get_unix_timestamp` function using ruster_unsafe, compiled ok, when i run `l PiNif` in iex, the following error raised.

```
iex(1)> l PiNif
{:error, :on_load_failure}
iex(2)> 
16:36:13.811 [warn]  The on_load function for module Elixir.PiNif returned {:error, {:bad_lib, 'Function not found \'Elixir.PiNif\':get_unix_timestamp/0'}}
```

Source code of my project 
https://github.com/developerworks/elixir_rust_interop_demo

**Comment by goertzenator** [comment]
I reviewed your code and everything looks okay, so I'm stumped at the moment.  Some things to try to understand the error better:
- Change the order of the `nif!` declarations.
- Add an additional `nif!` to the list for a simple test function.
- Change `get_unix_timestamp` so it just returns an atom and calls nothing else.
- Change the name of `get_unix_timestamp` to something else.

**Comment by developerworks** [comment]
### FIXED:

The error was fixed by add a [stub function](http://erlang.org/doc/man/erlang.html#nif_error-1) in `pi_nif.ex` elixir module, i forgot that before. 
Add this the following snippet to `pi_nif.ex`

https://github.com/developerworks/elixir_rust_interop_demo/commit/37594781c76a5fd3c74ac930a81aa752d2000f07#diff-a7c66a59f6b315ac9708235612ffcb10R45

```
@spec get_unix_timestamp :: non_neg_integer
def get_unix_timestamp do
  :erlang.nif_error({:nif_not_loaded, @mod})
end
```
